brew 'awscli'
brew 'bash-completion'
brew 'bat'
brew 'code-minimap'
brew 'coreutils'
brew 'fd'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'go'
brew 'golangci-lint'
brew 'gopls'
brew 'goreleaser'
brew 'jq'
brew 'mockery'
brew 'node'
brew 'opa'
brew 'ripgrep'
brew 'semgrep'
brew 'starship'
brew 'tmux'
brew 'tree'
brew 'vault'
brew 'vim'
brew 'xsv'
brew 'yamllint'

cask 'alt-tab'
cask 'rectangle'

tap 'hashicorp/tap'
brew 'hashicorp/tap/terraform-ls'

tap 'miniscruff/changie', 'https://github.com/miniscruff/changie'
brew 'changie'
