# ~/.config/starship.toml

# Don't print a new line at the start of the prompt
add_newline = false

[username]
show_always = true

[hostname]
ssh_only = false
disabled = false
style = "yellow"
format = "[⟪$hostname⟫]($style) in "

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "
vicmd_symbol = "[](bold yellow) "
